language: python
python:
    - "3.4"
    - "3.6"
dist: trusty
sudo: required

cache:
  directories:
  - bincache

git:
  submodules: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zlib1g-dev libncurses5-dev python3-all-dev libhdf5-dev libatlas-base-dev libopenblas-base libopenblas-dev libbz2-dev liblzma-dev libffi-dev

script:
  - echo $TRAVIS_PYTHON_VERSION
  - make install
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then make docs; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHPAGES_TOKEN
  local_dir: docs/_build/html
  target_branch: gh-pages
  on:
    branch: master
    python: "3.4"
